CREATE DATABASE MUSICPLAYER
USE MUSICPLAYER

CREATE TABLE MUSIC(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50),
    FILEPATH VARCHAR(255),
	IMAGE VARCHAR(255)
);

CREATE TABLE PLAYLIST (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE MUSIC_PLAYLIST(
    ID INT PRIMARY KEY,
    MUSIC_ID INT,
    PLAYLIST_ID INT
);

ALTER TABLE MUSIC_PLAYLIST
ADD CONSTRAINT FK_MP_MS
FOREIGN KEY (MUSIC_ID) REFERENCES MUSIC  (ID);

ALTER TABLE MUSIC_PLAYLIST
ADD CONSTRAINT FK_MP_PL
FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST  (ID);

SELECT * FROM MUSIC